const test = require("ava");

test.todo("isNameValid - validation of valid name should be positive")
test.todo("isNameValid - validation of invalid name should be negative")
test.todo("isDateValid - validation of valid date should be positive")
test.todo("isDateValid - validation of invalid date should be negative")
test.todo("isIdValid - validation of valid id should be positive")
test.todo("isIdValid - validation of invalid id should be negative")
test.todo("isOwnerValid - validation of valid owner should be positive")
test.todo("isOwnerValid - validation of invalid owner should be negative")
test.todo("isTagsValid - validation of valid tags should be positive")
test.todo("isTagsValid - validation of invalid tags should be negative")
test.todo("isIconValid - validation of valid icon should be positive")
test.todo("isIconValid - validation of invalid icon should be negative")
test.todo("isSourceValid - validation of valid source should be positive")
test.todo("isSourceValid - validation of invalid source should be negative")